CSU DSCI 369 Lab 6
Instructor: Emily J. King
Spring 2024

Goals: Working with algbraic properties of transposes and inverses.




In [1]:
import numpy as np
from numpy import linalg as LA

Let A be a random 3x3 matrix.

In [2]:
A=np.random.rand(3,3)

Compute the transpose of A.

In [3]:
np.transpose(A)

array([[0.64820518, 0.9787317 , 0.29357383],
       [0.21361218, 0.59518122, 0.0207747 ],
       [0.10377669, 0.98504566, 0.50404872]])

Let B be another new random 3x3 matrix and compute its transpose.

In [4]:
B=np.random.rand(3,3)
np.transpose(B)

array([[0.74715926, 0.42796156, 0.97080806],
       [0.48939927, 0.00646285, 0.31555945],
       [0.0083561 , 0.10865455, 0.87219137]])

Compute AB.

In [5]:
A@B

array([[0.67647755, 0.3513594 , 0.11913953],
       [1.94227341, 0.79367762, 0.93199584],
       [0.71757174, 0.30286642, 0.44433734]])

Compute BA

In [6]:
B@A

array([[0.96575622, 0.45105716, 0.56383022],
       [0.31563043, 0.09752164, 0.10554583],
       [1.19418341, 0.413311  , 0.85121466]])

Test if these are the same.

In [7]:
np.allclose(A@B,B@A)

False

Compute the inverse of AB

In [8]:
LA.inv(A@B)

array([[ -3.82494274,   6.52278674, -12.65594342],
       [ 10.55539277, -11.6879457 ,  21.68521836],
       [ -1.01770239,  -2.56715132,   7.90800733]])

Test if (AB)^(-1) is equal to A^(-1)B^(-1)

In [9]:
np.allclose(LA.inv(A@B),LA.inv(A)@LA.inv(B))

False

Test if (AB)^(-1) is equal to B^(-1)A^(-1).

In [10]:
np.allclose(LA.inv(A@B),LA.inv(B)@LA.inv(A))

True

How does this agree with what we've seen in class?


Compute the transpose of AB.

In [11]:
np.transpose(A@B)

array([[0.67647755, 1.94227341, 0.71757174],
       [0.3513594 , 0.79367762, 0.30286642],
       [0.11913953, 0.93199584, 0.44433734]])

Test if (AB)^T is equal to (A^T)(B^T).

In [12]:
np.allclose(np.transpose(A@B),np.transpose(A)@np.transpose(B))

False

Test if (AB)^T is equal to (B^T)(A^T)

In [13]:
np.allclose(np.transpose(A@B),np.transpose(B)@np.transpose(A))

True

How does this agree with what we've seen in class?



Exercises
1. a. Compute the inverse of A^4.

In [14]:
inv_pow = LA.inv(LA.matrix_power(A,4))

b. Compute the fourth power of the inverse of A.


In [15]:
pow_inv = LA.matrix_power(LA.inv(A),4)

c. Are the answers to a. and b. the same?
Yes


In [16]:
np.allclose(pow_inv,inv_pow)

True

2. a. Compute the inverse of A+B.


In [31]:
inv_sum = LA.inv(A + B)

b. Compute the sums of the inverses of A and B.


In [32]:
sum_inv = LA.inv(A) + LA.inv(B)

c. Are the answers to a. and b. the same?


In [33]:
np.allclose(inv_sum, sum_inv)

False

3. a. Compute the matrix-vector product of A^(-1) times the first column of A.


In [24]:
LA.inv(A) @ (A[:,0])

array([ 1.00000000e+00, -1.12984333e-17, -1.30928611e-16])

b. Compute the matrix-vector product of A^(-1) times the second column of A.


In [25]:
LA.inv(A) @ (A[:,1])

array([ 1.11596804e-16,  1.00000000e+00, -5.38600461e-17])

c. Compute the matrix-vector product of A^(-1) times the third column of A.


In [30]:
LA.inv(A) @ (A[:,2])

array([-7.07239915e-17,  2.78892231e-17,  1.00000000e+00])

d. Why do the answers to a.-c. make sense?
The answers to a-c are essentially an identity matrix because the diagonal is all 1's and the other values are so small that they are essentially zero (probably not exactly zero due to floating point arithmetic). It makes sense that this operation would generate an identity matrix because you get an identity matrix when you multiply a matrix by its inverse and by multiplying each column by the inverse you're doing basically the same thing.
