CSU DSCI 369 Lab 13
Instructor: Emily J. King
Spring 2024

Goals: Get more (now explicit) practice with eigenvectors and eigenvalues.
Play around with power iteration to find an eigenvector for the largest eigenvalue.

In [1]:
import numpy as np
from numpy.linalg import norm
from numpy.linalg import eigvals
from numpy.linalg import eig
from numpy.linalg import inv
from poweriter import poweriter

Eigenvalues of diagonal matrices

Recall what multiplying by a diagonal matrix does: it scales the first coordinate by the first diagonal element, the second coordinate by the second diagonal element, and so on.  So, what should the eigenvalues and eigenvectors be?  Discuss.

Now we test by making a 5x5 diagonal matrix.

In [2]:
F=np.diag(np.array([5, 1, 4, 2, 3]))
F

array([[5, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3]])

Let's compute the eigenvalues alone.

In [3]:
eigvals(F)

array([5., 1., 4., 2., 3.])

Notice that the eigenvalues are simply the diagonal elements of the diagonal matrix, but they may be listed in a different order due to the algorithm used to compute them.  

Now let's see the command to compute the eigenvalues and eigenvectors.

In [4]:
d, U = eig(F)
d

array([5., 1., 4., 2., 3.])

In [5]:
U

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Notice the eig command returns an array and a matrix. The array is the same thing returned by eigvals. When possible, the matrix returned is an orthogonal matrix: that is, the columns form an orthonormal basis for R^n. Otherwise, the columns are unit norm but not necessarily orthogonal. The columns of the matrix are eigenvectors corresponding to the eigenvalues listed in the array.  IF it is possible to decompose a matrix in the form UDU^(-1) that we've played around with for the last 3 labs, then U above and D formed as the diagonal matrix with diagonal d above, will work.

Let's test.

In [6]:
np.allclose(U@np.diag(d)@inv(U),F)

True

They are the same.

Note that any scalar multiple of the jth column of U above is still an eigenvector for the jth eigenvalue since eigenspaces are vector spaces.

Now let's test another diagonal matrix: the 7x7 identity matrix.

In [7]:
E=np.eye(7)
E

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

What do you think the eigenvalues and eigenvectors are? Discuss.

In [8]:
d, U = eig(E)
d

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
U

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

How can you interpret what you see?  

Also note that an eigenvalue can be repeated if the eigenspace is larger than 1 dimension.  In that case, the eigenvectors returned corresponding to the same value are an orthonormal basis for the space.

Eigenvalues of MDM^(-1)

We've been playing with matrices of this form for 3 labs now.  Now, let's explicitly compute the eigenvalues / eigenvectors.  To make the patterns easier to see, we will use an integer matrix.

In [10]:
M=np.array([[-3, -3, -3, -3, 0],[2, -3, -2, -2, 0],[-1, 3, -1, 1, -1],[-2, 3, 2, 2, 2],[-1, 1, -3, 1, -2]])
M


array([[-3, -3, -3, -3,  0],
       [ 2, -3, -2, -2,  0],
       [-1,  3, -1,  1, -1],
       [-2,  3,  2,  2,  2],
       [-1,  1, -3,  1, -2]])

Let's remember what the diagonal matrix above looked like and then compute MFM^(-1):


In [11]:
F

array([[5, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3]])

In [59]:
A=M@F@inv(M)
A

array([[ 3.5       ,  0.21428571,  0.85714286,  1.5       ,  1.07142857],
       [-1.        ,  5.71428571,  2.85714286,  1.        , -0.42857143],
       [ 0.5       , -1.        ,  0.        ,  0.        ,  1.5       ],
       [ 1.        , -2.71428571, -2.85714286,  2.        ,  0.42857143],
       [ 0.5       ,  0.35714286, -0.57142857,  0.5       ,  3.78571429]])

Let's compute the eigenvalues.


In [13]:
eigvals(A)

array([5., 2., 1., 4., 3.])

What do you see? Discuss.

Let's compute the eigenvalues and eigenvectors.

In [14]:
d_A, U_A = eig(A)
d_A

array([5., 2., 1., 4., 3.])

In [15]:
U_A

array([[ 6.88247202e-01, -6.88247202e-01,  4.93196962e-01,
        -5.77350269e-01,  4.93888830e-16],
       [-4.58831468e-01, -4.58831468e-01,  4.93196962e-01,
        -3.84900179e-01,  2.82616643e-15],
       [ 2.29415734e-01,  2.29415734e-01, -4.93196962e-01,
        -1.92450090e-01, -3.33333333e-01],
       [ 4.58831468e-01,  4.58831468e-01, -4.93196962e-01,
         3.84900179e-01,  6.66666667e-01],
       [ 2.29415734e-01,  2.29415734e-01, -1.64398987e-01,
        -5.77350269e-01, -6.66666667e-01]])

So, what's going on?  From the ordering of the output, the first column of U_A corresponds to the eigenvalue of 5.  From the previous labs, we know that since 5 is the first entry of the diagonal matrix F, if we multiply A times the first column of M, it must be 5 times that column.  Let's normalize that column:


In [16]:
M[:,0]/norm(M[:,0])


array([-0.6882472 ,  0.45883147, -0.22941573, -0.45883147, -0.22941573])

That should look like either the first column or negative the first column of U_A.  Let's test (replace the minus with plus if looks negated):

In [17]:
np.allclose(-M[:,0]/norm(M[:,0]),U_A[:,0])

True

Eigenvectors of non-diagonalizable matrices

Until now in the labs, we were always playing with matrices of the form MDM^(-1) for M nxn invertible and D nxn diagonal. Let's now consider a matrix that cannot be written in that form, a shear matrix.

Let S be a 2x2 matrix that shears by a factor of 3 downwards.  What do we know must stay in place?

In [18]:
S=np.array([[1, 0],[-3, 1]])


Now, we are going to compute the eigenvalues of S.


In [19]:
eigvals(S)

array([1., 1.])

Note that there are 2 ones. Does that mean that there are two dimensions of vectors in R^2 fixed by shearing?  Does that make sense?


In [20]:
d, U = eig(S)
d

array([1., 1.])

In [21]:
U

array([[0.00000000e+00, 7.40148683e-17],
       [1.00000000e+00, 1.00000000e+00]])

Now, we can hopefully see what has happened.  Both columns of U are the same (up to floating point arithmetic).  In particular, that means that U is not invertible, and thus UDU^(-1) isn't defined.  Let's check:

In [22]:
inv(U)

array([[-1.35107989e+16,  1.00000000e+00],
       [ 1.35107989e+16,  0.00000000e+00]])

Numpy should have returned a warning since the two columns were within floating point arithmetic of each other.  Instead, it returned a garbage matrix that has almost the largest number the computer can handle in one entry, and minux that number in another.  In real life, this matrix is not invertible.

The issue is that S is 2x2 but only has one dimension of eigenvectors: the y-axis.  Said another way: S only has one eigenspace, for eigenvalue 1, and that eigenspace is only 1-dimensional.

Power iteration

When a matrix is "nice enough", if you take a random vector and multiply it by higher and higher powers of the matrix, you get output that points closer and closer to the direction of an eigenvector for the largers eigenvalue.  We saw this a bit when playing around with the transition matrix: higher powers applied to the two starting vectors we tried (sunny today vs. gray today) always emphasized the steady state vector.  

We can do this for other matrices which have largest eigenvalue larger than 1. To make sure that the vector norms aren't getting too big for the computer, we can normalize.  So, the idea is, multiply a random vector by our matrix, normalize this output, then mulitply that by the matrix and repeat.  Take a look at the code in poweriter.py and discuss.

Let's try this with the transition matrix from lecture:

In [23]:
P=np.array([[9/10, 1/2],[1/10, 1/2]])
xout=poweriter(P,np.random.rand(2),1000)
xout

array([0.98058068, 0.19611614])

Now let's compare the normalization of the vector we know to be the steady state vector (i.e., a vector with eigenvalue 1, while the other eigenvalue is 2/5 < 1) to the output:

In [24]:
np.allclose(xout,np.array([5/6, 1/6])/norm(np.array([5/6, 1/6])))

True

We can see that power iteration output the normalization of the steady state vector.

Now let's do the same thing with the matrix A above. 


In [25]:
xout=poweriter(A,np.random.rand(5),1000)

The first column of U_A is an eigenvector for the largest eigenvalue. It is already normalized, so we can directly compare it to the output of power iteration. If you get false, negate the column from U_A and try again.

In [26]:
np.allclose(xout,U_A[:,0])

False

Exercises

1a. Normalize the other columns of M.

In [64]:
M[:,1]/norm(M[:,1])
M[:,2]/norm(M[:,2])
M[:,3]/norm(M[:,3])
M[:,4]/norm(M[:,4])

array([ 0.        ,  0.        , -0.33333333,  0.66666667, -0.66666667])

b. Test to see if they are the same with the "correct corresponding" column of U_A.


In [65]:
print(np.allclose(-M[:,1]/norm(M[:,1]),U_A[:,2]))
print(np.allclose(M[:,2]/norm(M[:,2]),U_A[:,3]))
print(np.allclose(M[:,3]/norm(M[:,3]),U_A[:,1]))
print(np.allclose(M[:,4]/norm(M[:,4]),U_A[:,4]))

True
True
True
True


c. Explain why this makes sense.


It is possible that the columns of M and columns of U_A will be out of order because the eigenvalues are simply the diagonal elements of the diagonal matrix, but they may be listed in a different order due to the algorithm used to compute them.

2a. Make a random symmetric 3x3 matrix using the code below.  (A symmetrix matrix is equal to its own transpose.)


In [66]:
C=np.random.rand(3,3)
C=C+np.transpose(C)
C

array([[0.37451746, 0.75833217, 1.31750618],
       [0.75833217, 1.20997381, 0.89849543],
       [1.31750618, 0.89849543, 1.15257419]])

b. Run power iteration to find the largest eigenvalue and a corresponding eigenvector.


In [67]:
fout=poweriter(C,np.random.rand(3),1000)

c. Use Matlab code to directly find the eigenvectors and eigenvalues.


In [70]:
eigenvalues, eigenvectors = eig(C)
print(eigenvalues)
print(eigenvectors)

[ 2.93600724 -0.6138483   0.41490651]
[[-0.50373875 -0.81308979  0.29177435]
 [-0.56257265  0.05245654 -0.82508201]
 [-0.65556028  0.57977005  0.48384647]]


I dont have Matlab so I ran the command used above