CSU DSCI 369 Lab 11
Instructor: Emily J. King
Spring 2024

Goals:  Play around with matrix algebra.  Tease null space / kernel and column space / image.

In [1]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv
from numpy.linalg import matrix_rank as rank
from scipy.linalg import null_space as null

We first consider a 5x6 matrix A.

In [2]:
A=np.array([[3, 10, -2, 2, 4, -6],[4, 8, 0, 0, 0, 0],[-3, 1, 4, 7, 3, 1],[4, -3, 4, 1, -3, 7],[1, 3, -3, -4, -1, -2]])
A

array([[ 3, 10, -2,  2,  4, -6],
       [ 4,  8,  0,  0,  0,  0],
       [-3,  1,  4,  7,  3,  1],
       [ 4, -3,  4,  1, -3,  7],
       [ 1,  3, -3, -4, -1, -2]])

Now we compute the dimension of the span of the columns of A.

In [3]:
rank(A)

4

So, this means that the columns are linearly dependent, since the rank is smaller than the number of vectors.  We are going to explore this a bit more.

In [4]:
N=null(A)
N

array([[-3.41607085e-17, -1.21163763e-16],
       [ 4.02540894e-17,  1.59980391e-17],
       [ 5.51918989e-01, -6.01707651e-01],
       [ 2.48943310e-02,  5.76813320e-01],
       [-6.01707651e-01, -5.51918989e-01],
       [-5.76813320e-01,  2.48943310e-02]])

The null command returns an orthonormal basis (a basis where the vectors are orthonormal), listed as columns, for the so-called nullspace/kernel of the matrix A.  We will learn about nullspace/kernels this week.  The basic definition is that the nullspace is the set of all vectors, which when multiplied on the left by the matrix, become the 0 vector.  Since null(A) returns a basis for the nullspace, this means that every vector that goes to zero under multiplication by this matrx is a linear combination of the vectors returned by null(A). Also note that since  null(A) returns a basis for the nullspace, we now know that the nullspace of this particular matrix has dimension 2. Let's play with this.

First note that the vectors returned by null(A) are in R^6.  So, we can multply them by the 5x6 matrix A.

Multiplying the first vector:


In [5]:
A@N[:,0]

array([ 0.00000000e+00,  1.85389881e-16, -5.55111512e-16,  0.00000000e+00,
        4.44089210e-16])

Notice that we get the zero vector in R^5.  (Or at least the zero vector up to floating point arithmetic.)

Now we multiply the second vector:

In [6]:
A@N[:,1]

array([ 4.16333634e-16, -3.56670739e-16,  3.74700271e-16, -9.29811783e-16,
        1.38777878e-16])

We again get the zero vector in R^5.

Now we multiply a random linear combination, using np.random.normal() (with no inputs) to generate single random scalars.

In [7]:
A@(np.random.normal()*N[:,0]+np.random.normal()*N[:,1])

array([-4.44089210e-16,  8.05515684e-17,  2.22044605e-16,  2.22044605e-16,
        0.00000000e+00])

We can keep running the above command multiple times with different random linear combinations and still get the zero vector.
Let's notice another thing: The number of columns of A is 6, dimension of span of columns of A is 4, and the dimension of the nullspace of A is 2, where 4+2=6.  

This is not a coincidence, as we'll see this week in lecture.

Let's consider a different matrix.  This one a 4x4 matrix B.

In [8]:
B=np.array([[1, 2, 0, -2],[2, 1, 4, 2],[2, -3, -1, -2],[-2, -3, 1, 0]])
B

array([[ 1,  2,  0, -2],
       [ 2,  1,  4,  2],
       [ 2, -3, -1, -2],
       [-2, -3,  1,  0]])

Now we compute the dimension of the span of the columns of B.

In [9]:
rank(B)

4

Note that there are 4 columns in B.  Thus, since the rank of B is 4, the columns are a basis for their span.  Further note that each column has 4 entries.  This means that the columns are a basis for all of R^4.  (Their span is all of R^4 and they are linearly independent.)

Now let's use the null command on B.

In [10]:
null(B)

array([], shape=(4, 0), dtype=float64)

It is empty because the only vector that B multplies to get the zero vector is the zero vector. The dimension of the nullspace is 0. I.e., if Bx = 0, it must be true that x=0. 

Again note that the dimension of the nullspace (0) plus the dimension of the span of the columns (4) is equal to the number of columns (4).

We also note that B is a square matrix that doesn't send a vector which isn't the zero vector to the zero vector.  We will see this week that this means that it doesn't collapse down any dimensions, i.e., B is invertible, which we check here by vertifying that the determinant is not 0:

In [11]:
det(B)

-146.0

We'll now play around with a specific 5x5 diagonal matrix D.

In [12]:
D=np.diag(np.array([2, 0, 5, 0, 1]))
D


array([[2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

Geometrically, what does multiplying vectors in R^5 by this matrix do to them? Discuss this with the class.

Now let's compute the rank.

In [13]:
rank(D)

3

This should make sense. Clearly, the second and fourth columns make the set linearly dependent.  (Like in the HW.) The second column can, for example, be written as 0 times the first column.  Thus, it is a linear combination of other columns.  Same goes for the fourth column.  However, the first, third, and fifth columns can't be written as linear combinations of one another.  E.g., there's no way to make a linear combination of the third and fifth columns to get the 2 entry in the first position of the first column.

Given the formula we noted earlier, we should get that the dimension of the nullspace is 2.

In [14]:
null(D)

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.]])

Notice that these two vectors have a single non-zero entry each, in the second and fourth positions.  We'll discuss this more in lecture.

We'll now play around with a random 5x5 orthogonal matrix U.  You don't need to understand the code to generate the random orthogonal matrix.  This is built on linear algebra that we won't do in this class.

In [15]:
U=np.linalg.qr(np.random.randn(5,5))[0]
U

array([[-4.93003405e-01,  3.70557172e-01, -4.84482343e-01,
        -5.60473584e-01, -2.66047450e-01],
       [-3.72670635e-04, -1.62677903e-02, -7.46303700e-01,
         6.62771524e-01, -5.91600676e-02],
       [ 4.04775525e-01,  2.50573977e-01, -3.17093179e-01,
        -2.81922940e-01,  7.70286199e-01],
       [ 7.51513608e-01,  2.97031282e-01, -7.58738674e-02,
        -1.28587477e-01, -5.69831669e-01],
       [ 1.68319859e-01, -8.43449963e-01, -3.19378644e-01,
        -3.88056677e-01, -8.75778589e-02]])

Let's test that U is indeed orthogonal, using the fact that a square matrix is orthogonal if and only if its transpose is its inverse, i.e., UU^T = I.

In [16]:
np.allclose(U@np.transpose(U),np.eye(5))

True

Since it is invertible, we should expect that the rank is equal to the number of columns and the nullspace is just the zero vector.


In [17]:
rank(U)

5

In [18]:
null(U)

array([], shape=(5, 0), dtype=float64)

Is U a rotation?  Remember that an orthogonal matrix is a rotation if and only if its determinant is 1.

In [19]:
det(U)

1.0000000000000004

As reminders: (1) There are many matrices which have determinant 1 but are not rotations.  For example, all shear matrices have determinant 1 but change angles between vectors. (2) Although all reflections are orthogonal and all reflections have determinant -1, all orthogonal matrices with determinant -1 are not necessarily reflections.  They can be a complication combination of reflections and rotations.

Exercises

1. Let D and U be the matrices defined above.  Set M=U*D*U^(-1).

In [36]:
M=U@D@inv(U)

2. Set u2 = second column of U and u4 = fourth column of U. (Counting starting at one.  Adjust one Python.)


In [37]:
u2 = U[:,1]
u4 = U[:,3]

3. Multiply M times u2.  Then discuss the outcome.  How does this relate to Lab 10's exercises?


In [38]:
M@u2

array([-4.84832568e-17,  1.39030540e-16, -2.78493564e-17,  4.11487094e-17,
        1.05635295e-17])

The outcome of this transformation is a zero vector. Since U is a rotation matrix, this transformation must rotate u2 by some degree then scale the vector by D, and rotate it back to the starting position. Since D is a diagonal matrix with non-zero entries, I suspect that the first rotation moves u2 onto one of the axis. This is similar to C from lab 10, which also resulted in 0 vectors when the transformation was applied.

4.  Multiply M times u4.  Then discuss the outcome.  How does this relate to Lab 10's exercises?


In [24]:
M@u4

array([-3.18674214e-16, -4.24246920e-16,  3.69841403e-17,  1.60491592e-16,
       -1.43122236e-16])

I think that a very similar thing happens to u4 in this transformation.  It is rotated by some degree, scaled by D, then rotated back.  Since multiplying M by u4 also returns a 0 vector, I believe that M must also be similar to transformation C from lab 10.  After the first rotation, the vector was probably rotated onto one of the axis.

5. Calculate the rank of M.


In [35]:
rank(M)

3

6. Calculate a basis for the nullspace of M.


In [39]:
null(M)

array([[ 0.67186027,  0.00685851],
       [-0.55821277, -0.35767196],
       [ 0.37389229, -0.04972341],
       [ 0.27287056, -0.17408038],
       [-0.15082604,  0.91610443]])

7. Discuss your answers to 5 and 6.


Since the rank (3) is less than the number of columns of M, the column vectors must be linearly dependent.  The vectors in the basis of the nullspace of M have a dimension of 5, which makes sense because M is a 5x5 matrix.

8. Is u2 a linear combination of the columns from the answer in Exercise 6?  Discuss your answer.


Yes, u2 is a linear combination of the columns because M@u2 is equal to the 0 vector.  Any linear combination of basis vectors for nullspace A times that vector is 0.