CSU DSCI 369 Lab 2
Instructor: Emily J. King
Spring 2024

Goals: Learn how to calculate and interpret basic linear operations. Recall that floating point arithmetic doesn't always give the exact same output. Understand the output of squaring adjacency matrices before learning how squaring a matrix is defined. Visually explore linear combinations.

Additional files needed: DSCI369_Sp24_Lab2.pdf

In [1]:
import numpy as np # used for most math functions
from numpy import linalg as LA # some special linear algebra functions

Part 1

Define a random vector x with 6 entries. (If you don't know probability, just take "random" to mean something that a human wouldn't likely write down if asked for a vector. If you know probability, each entry is a draw independently from the uniform [0,1] probability distribution.)

In [2]:
x = np.random.rand(6)
print(x)

[0.99466052 0.87742881 0.13986442 0.2178267  0.10773335 0.18520655]


Define an all-ones vector y with 6 entries.

In [3]:
y = np.ones(6)
print(y)

[1. 1. 1. 1. 1. 1.]


Add together x and y.

In [4]:
x+y

array([1.99466052, 1.87742881, 1.13986442, 1.2178267 , 1.10773335,
       1.18520655])

Scalar multiply y by 2.1 and call this new vector z.

In [5]:
z=2.1*y
print(z)

[2.1 2.1 2.1 2.1 2.1 2.1]


Scalar multiply x by 4 and call this new vector v.

In [6]:
v=4*x
print(v)

[3.97864208 3.50971523 0.55945769 0.87130679 0.43093339 0.74082621]


Add together v and z.

In [7]:
v+z

array([6.07864208, 5.60971523, 2.65945769, 2.97130679, 2.53093339,
       2.84082621])

Now, add together 2.1y and 4x.

In [8]:
2.1*y+4*x

array([6.07864208, 5.60971523, 2.65945769, 2.97130679, 2.53093339,
       2.84082621])

Test to see if the two previous operations yielded the same vector.  We will not learn what "norm" means for another week or so, but for now just think of it as a generalization of absolute value for vectors; so, if two vectors computed with floating point arithmetic are "the same", the norm of their difference should be really close to 0.  Here, 1 means that the inequality is true and 0 means that it's false.  In this class, whenever we want to test if two vectors using floating point arithmetic are the same, we will use the command np.allclose(vec1,vec2).

In [9]:
np.allclose(v+z,2.1*y+4*x)

True

Define a random 3x4 matrix M.

In [10]:
M = np.random.rand(3,4)
print(M)

[[0.08498037 0.70893827 0.83235136 0.72608912]
 [0.44137169 0.27697609 0.23326762 0.69775156]
 [0.49158507 0.62445893 0.98799556 0.28557421]]


Part 2

Now we enter the adjancency matrix of the graph from class.

In [18]:
A = np.array([[0, 1, 0, 0, 1, 0], [1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 0], [0, 0, 1, 0, 1, 1], [1, 1, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0]])
print(A)

[[0 1 0 0 1 0]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 1]
 [1 1 0 1 0 0]
 [0 0 0 1 0 0]]


We will learn in the coming weeks the mathematical definition of exponentiation of matrices that have an equal number of rows and columns.  If you have done programming before, this is likely a different operation than what you've seen. DO NOT USE ** for matrix exponentiation -- IT IS NOT CORRECT! In any case, we are going to see what this squaring does to adjacency matrices.

In [19]:
LA.matrix_power(A,2)

array([[2, 1, 1, 1, 1, 0],
       [1, 3, 0, 2, 1, 0],
       [1, 0, 2, 0, 2, 1],
       [1, 2, 0, 3, 0, 0],
       [1, 1, 2, 0, 3, 1],
       [0, 0, 1, 0, 1, 1]])

With the TA and the other students in the lab, discuss what you think that means.  For example, the (1,1) entry of A^2 is 2, and the (3,4) entry of A^2 is 3.  What property of the first vertex with itself occurs twice and with the third and fourth occurs three times?  Now let's try cubing the adjancency matrix.

In [20]:
LA.matrix_power(A,3)

array([[2, 4, 2, 2, 4, 1],
       [4, 2, 5, 1, 6, 2],
       [2, 5, 0, 5, 1, 0],
       [2, 1, 5, 0, 6, 3],
       [4, 6, 1, 6, 2, 0],
       [1, 2, 0, 3, 0, 0]])

Again, discuss the output.

Exercises (11 points total)
1.  Generate a random row vector with 10 entries.  Call that vector p.


In [12]:
p = np.random.rand(10)
print(p)

[0.87027902 0.99160739 0.7285031  0.96347735 0.43782869 0.96191567
 0.29960972 0.43668044 0.59906212 0.59425165]


2. Make an all-zeros vector with 10 entries.  Call that vector q.  (Hint: Using a command from last week will make this easier.)


In [14]:
q = np.zeros(10)
print(q)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Scalar multiply q by 1000 and add it to p.

In [16]:
p += 1000 * q
print(p)

[0.87027902 0.99160739 0.7285031  0.96347735 0.43782869 0.96191567
 0.29960972 0.43668044 0.59906212 0.59425165]


4. Interpret output of exercise 3.  What happened?

Nothing happened because q is an all-zeros vector so multiplying it by a scalar won't change its entries.  Since the scalar multiplication didn't change anything, you're effectively doing p += 0, which won't change p.

5. Enter the adjacency matrix for the blue graph on 3 vertices from the lab sheet. Call the matrix A1.


In [24]:
A1 = np.array([[0,1,0],[1,0,1],[0,1,0]])
print(A1)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


6. Square the matrix A1.

In [23]:
LA.matrix_power(A1,2)

array([[1, 0, 1],
       [0, 2, 0],
       [1, 0, 1]])

7. Enter the adjacency matrix for the black graph on 4 vertices from the lab sheet. Call the matrix A2.


In [25]:
A2 = np.array([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]])
print(A2)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


8. Square the matrix A2.

In [26]:
LA.matrix_power(A2,2)

array([[3, 2, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 3, 2],
       [2, 2, 2, 3]])

9. Enter the adjacency matrix for the green graph on 5 vertices from the lab sheet. Call the matrix A3.


In [27]:
A3 = np.array([[0,1,0,0,1],[1,0,1,0,0],[0,1,0,1,0],[0,0,1,0,1],[1,0,0,1,0]])
print(A3)

[[0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [1 0 0 1 0]]


10. Square the matrix A3.

In [28]:
LA.matrix_power(A3,2)

array([[2, 0, 1, 1, 0],
       [0, 2, 0, 1, 1],
       [1, 0, 2, 0, 1],
       [1, 1, 0, 2, 0],
       [0, 1, 1, 0, 2]])

11. Interpret the output of exercises 6, 8 and 9.  Does this match with the in-lab discussion?

The outputs of exercises 6, 8 and 9 do match our in-lab discussion.  By squaring the adjacency matrix you can reveal how many edges are connected to a node.  For example, in A1, node 1 is represented by the entry (1,1) and has a value of 1.  This means that there is one edge connected to node 1, which is true if we look at the graph.  Likewise, for node 2, the entry (2,2) has a value of 2 because node 2 has two edges attached to it.