CSU DSCI 369 Lab 12
Instructor: Emily J. King
Spring 2024

Goals:  Learn how to generate solutions to systems of equations.  Final eigenvalue/eigenvector teaser.

In [1]:
import numpy as np
from scipy.linalg import null_space as null
from numpy.linalg import lstsq as lsqr
from numpy.linalg import inv

Traffic Problem

Let's write the traffic problem as a matrix equation Ax=b.

In [2]:
A=np.array([[1, -1, 0, 0],[0, 1, -1, 0],[0, 0, 1, -1],[-1, 0, 0, 1]])
b=np.array([160,-40,210,-330])

The following command will return a solution to the least squares problem minimizing ||Ax-b||.  Note that any solution to Ax=b must be a solution to least squares since then the Euclidean distance between Ax and b would be 0.  I.e., the min ||Ax-b||^2 = 0 if and only if Ax=b has a solution.

In [3]:
x1=lsqr(A,b,rcond=None)[0]
x1

array([ 152.5,   -7.5,   32.5, -177.5])

Let's test to see if this is indeed a solution to the original equation.

In [4]:
np.allclose(A@x1,b)

True

You should have gotten True since this system has a solution.  Most likely, however, the given solution isn't feasible for the orginal word problem (i.e., has negatve traffic flow).

Let's generate more solutions.  First we compute a basis for the nullspace of the coefficient matrix.

In [5]:
y=null(A)
y

array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

Recall that A*y = 0 for any y in the nullspace of A.  Thus, any vector in the span of the vector returned above can be added to x to get another solution to Ax=b.


In [6]:
x2=x1+np.random.normal()*y[:,0]
np.allclose(A@x2,b)

True

Let's try that again with another random element of the nullspace.


In [7]:
x3=x1+np.random.normal()*y[:,0]
np.allclose(A@x3,b)

True

Finally, notice that all of the entries of elements of the nullspace of A have the same value.  That is, the nullspace of A is precisely the one-dimensional subspace of R^4 consisting of vectors with all equal components.  Since this nullspace is particularly nice, we can actually easily find a feasible answer by adding in a bunch of positive numbers.  (This is typically not so easy to do just by inspection.)

In [8]:
x3=x1-np.min(x1)*2*y[:,0]
np.allclose(A@x3,b)

True

In [9]:
x3

array([330., 170., 210.,   0.])

Final eigenvector teaser

Let B be a random 5x5 matrix and D a random 5x5 diagonal matrix.

In [10]:
B=np.random.rand(5,5)
D=np.diag(np.random.rand(5))

In [11]:
B

array([[0.99910862, 0.16666853, 0.75870735, 0.36923839, 0.37082903],
       [0.00337104, 0.34663262, 0.56974838, 0.0473044 , 0.27799928],
       [0.63728874, 0.82204485, 0.71537969, 0.79744356, 0.28208737],
       [0.68702955, 0.06500415, 0.57585053, 0.33499748, 0.55886971],
       [0.94659429, 0.8333315 , 0.13858963, 0.39643815, 0.99197686]])

In [12]:
D

array([[0.90309576, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.51182438, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.1136022 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.2751273 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.87653506]])

Let's multiply a series of vectors/matrices.  Discuss the output.


In [13]:
inv(B)@B # Identity matrix

array([[ 1.00000000e+00,  6.22266697e-17,  1.11331519e-16,
         4.50618376e-17,  1.12127505e-17],
       [-1.82159731e-16,  1.00000000e+00,  1.04220644e-16,
         2.50103006e-17, -4.87832640e-17],
       [ 7.92057226e-17, -3.58212371e-17,  1.00000000e+00,
        -3.05513417e-17,  1.08629900e-16],
       [ 2.45457031e-16, -1.41511330e-16, -8.48033209e-17,
         1.00000000e+00,  1.88018629e-16],
       [ 1.44347050e-16,  4.42068890e-17,  2.40102350e-16,
         9.09269172e-17,  1.00000000e+00]])

In [14]:
inv(B)@B[:,0] # First column of identity matrix

array([ 1.00000000e+00, -1.82159731e-16,  7.92057226e-17,  2.45457031e-16,
        1.44347050e-16])

In [15]:
D@inv(B)@B[:,0] # First column of D

array([ 9.03095756e-01, -8.86634007e-17,  2.42028093e-17,  1.04070346e-16,
        3.01606902e-16])

In [24]:
B@D@inv(B)@B[:,0]

array([0.90229076, 0.00304437, 0.57553275, 0.62045347, 0.85486529])

In [30]:
B@D@inv(B)@B[:,1]/B[:,1] # one of the elements off the diagonal of D

array([0.51182438, 0.51182438, 0.51182438, 0.51182438, 0.51182438])

Discuss the output.

Exercises

Define M to be a random 3x6 matrix and c a random 3x1 vector. Test if there is a solution to Mx=c.  If there is a solution to Mx=c, give an additional solution to the problem.

In [18]:
M=np.random.rand(3,6)
c=np.random.rand(3,1)

sol=lsqr(M,c,rcond=None)[0]
np.allclose(M@sol,c)

True

In [20]:
nM=null(M)
sol2=sol+np.random.normal()*nM[:,0].reshape(6,1)
np.allclose(M@sol2,c)

True

2. Test more cases above.  What do you think will happen when you multiply B*D*B^(-1) times the jth column of B for any invertible dxd matrix B and any dxd diagonal matrix D.

BDB^(-1) describes a series of transformations applied to the jth column of B. The first transformation is B^(-1)@Bj which appears to turn Bj into the jth column of the identity matrix. Then, multiplying by D turns the vector into the jth column of D because only one value aligns with the 1 in the identity matrix column and the rest of the entries are 0. Finally, multiplying by B scales the jth column of B by the nonzero entry in the jth column of D. The rest of the columns in B would be multiplied by 0.